# -*- coding: utf-8 -*-
"""CSE221_Lab-01_Task-01(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mljwgB31WCrCuYu9MfPwQryWOBWP3m7u
"""

#Task- 01 b
file = open("input1b.txt", "r")
T = int(file.readline())
text = file.readlines()

output_file = open("output1b.txt", "a")

for i in range(T):
  x = text[i].split(" ")
  if x[2] == "+":
    output_file.write(f"The result of {int(x[1])} + {int(x[3])} is {int(x[1]) + int(x[3])} \n")
  elif x[2] == "-":
    output_file.write(f"The result of {int(x[1])} - {int(x[3])} is {int(x[1]) - int(x[3])} \n")
  elif x[2] == "*":
    output_file.write(f"The result of {int(x[1])} * {int(x[3])} is {int(x[1]) * int(x[3])} \n")
  elif x[2] == "/":
    output_file.write(f"The result of {int(x[1])} / {int(x[3])} is {int(x[1]) / int(x[3])} \n")

file.close()
output_file.close()