# -*- coding: utf-8 -*-
"""CSE221_Lab-01_Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_kwsB5ARcPKoWD1pqAvaGx7_guKidNjK
"""

#Task- 03
file = open("input3.txt","r")
N = int(file.readline())

id_arr = list(map(int, file.readline().split()))
marks_arr = list(map(int, file.readline().split()))

for i in range(N):
  max_idx = i
  for j in range(i+1, N):
    if marks_arr[j] > marks_arr[max_idx]:
      max_idx = j
    elif marks_arr[j] == marks_arr[max_idx]:
      if id_arr[j] < id_arr[max_idx]:
        max_idx = j

  P = id_arr[i]
  Q = marks_arr[i]
  marks_arr[i] = marks_arr[max_idx]
  id_arr[i] = id_arr[max_idx]
  id_arr[max_idx] = P
  marks_arr[max_idx] = Q

  output_file = open("output3.txt", "a")
  output_file.write(f"ID: {id_arr[i]} Mark: {marks_arr[i]}\n")

file.close()
output_file.close()