# -*- coding: utf-8 -*-
"""CSE221_Lab-01_Task-04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNrB6AhgFLsdfH7TNwvSZDdnL2raUmyr
"""

#Task- 04
file = open("input4.txt", "r")
N = int(file.readline())

schedule = file.readlines()
schedule[len(schedule)-1] = schedule[len(schedule)-1] + "\n"

for i in range(N):
  min_idx = i
  for j in range(i+1, N):
    x = schedule[j].split()
    y = schedule[min_idx].split()

    if x[0] < y[0]:
      min_idx = j
    elif x[0] == y[0]:
      if x[len(x) - 1] > y[len(x) - 1]:
        min_idx = j

  temp = schedule[i]
  schedule[i] = schedule[min_idx]
  schedule[min_idx] = temp

output_file = open("output4.txt", "a")
for i in range(len(schedule)):
  output_file.write(f'{schedule[i]}')

file.close()
output_file.close()