# -*- coding: utf-8 -*-
"""CSE221_Lab-04_Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cp6zJ1Nf3nBFLUzaq-m9CZbvnnrSqHgt
"""

#Task- 03
file = open("input3_3.txt", "r")
output_file = open("output3_3.txt", "a")
N, M = map(int, file.readline().split())
Adj_list = {}
for j in range(1, N+1):
  Adj_list[j] = []

for k in range(M):
  u, v = map(int, file.readline().split())
  Adj_list[u].append(v)
  Adj_list[v].append(u)

def DFS(G, u, path):
  path.append(u)
  for i in G[u]:
    if i not in path:
      DFS(G, i, path)
  return path

dfs_path = DFS(Adj_list, 1, [])

output_file.write(" ".join(map(str, dfs_path)))

file.close()
output_file.close()