# -*- coding: utf-8 -*-
"""CSE221_Lab-04_Task-01(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZdvHkUZnl-FY0jcSzYLVUFnsapNSqyJ
"""

#Task- 01 b
file = open("input1b_3.txt", "r")
output_file = open("output1b_3.txt", "a")
N, M = map(int, file.readline().split())
edges = []
for i in range(M):
  edges.append(list(map(int, file.readline().split())))

def create_adj_list(N, M, edges):
  adj_dict = {}

  for i in range(0, N+1):
    adj_dict[i] = []

  for j in edges:
    u, v, w = j
    adj_dict[u].append((v, w))

  return adj_dict

def print_adj_list(list):
  for p, q in list.items():
    output_file.write(f"{p} :" + " ")
    if q:
      for n, w in q:
        output_file.write(f"({n}, {w})" + " ")
      output_file.write("\n")
    else:
      output_file.write("\n")

adj_list = create_adj_list(N, M, edges)
print_adj_list(adj_list)

file.close()
output_file.close()