# -*- coding: utf-8 -*-
"""CSE221_Lab-04_Task-01(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7ppc2ITSJVMRb_lUka1phJlW-f2174R
"""

#Task- 01 a
import numpy as np
file = open("input1a_2.txt", "r")
output_file = open("output1a_2.txt", "a")
N, M = map(int, file.readline().split())
edges = []
for i in range(M):
  edges.append(list(map(int, file.readline().split())))

def create_adj_matrix(N, M, edges):
  adj_matrix = np.zeros((N+1, N+1), dtype=int)
  for j in edges:
    u, v, w = j
    adj_matrix[u][v] = w
  return adj_matrix

def print_adj_matrix(matrix):
  for r in matrix:
    output_file.write(" ".join(map(str, r)) + "\n")

adj_matrix = create_adj_matrix(N, M, edges)
print_adj_matrix(adj_matrix)

file.close()
output_file.close()