# -*- coding: utf-8 -*-
"""CSE221_Task-04_Lab-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vn1T73orZvS69Cbk8hVGhwmdt7qC2D-E
"""

#Task- 04
file = open("input4.txt", "r")

def max_possible_value(N, A):
  squared_max = [0] * N
  max_val = A[N - 1]

  for i in range(N - 2, -1, -1):
    squared_max[i] = max(squared_max[i + 1], A[i + 1] ** 2)

  max_result = float('-inf')
  for i in range(N - 1):
    value = A[i] + squared_max[i]
    max_result = max(max_result, value)

  return max_result

N = int(file.readline())
arr = list(map(int, file.readline().split()))

R = max_possible_value(N, arr)

output_file = open("output4.txt", "a")
output_file.write(str(R))

file.close()
output_file.close()