# -*- coding: utf-8 -*-
"""CSE221_Task-05_Lab-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-lsnmCa_NqWqNM54VDi2txq9iXemFi2
"""

#Task- 05
file = open("input5.txt", "r")

def quick_sort(arr, low, high):
  if low < high:
    pivot_idx = partition(arr, low, high)
    quick_sort(arr, low, pivot_idx - 1)
    quick_sort(arr, pivot_idx + 1, high)

  return arr

def partition(arr, low, high):
  pivot = arr[high]
  i = low - 1

  for j in range(low, high):
    if arr[j] <= pivot:
      i += 1
      arr[i], arr[j] = arr[j], arr[i]

  arr[i + 1], arr[high] = arr[high], arr[i + 1]

  return i + 1

N = int(file.readline())
arr = list(map(int, file.readline().split()))

R = quick_sort(arr, 0, N-1)

output_file = open("output5.txt", "a")
for r in R:
  output_file.write(str(r) + " ")

file.close()
output_file.close()