# -*- coding: utf-8 -*-
"""CSE221_Task-03_Lab-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTSHNbtyGSElMXCnJRjtpyc1PW7Vwkev
"""

#Task- 03
file = open("input3.txt", "r")

def merge_and_count(arr, left, mid, right):
  count = 0
  x = mid - left + 1
  y = right - mid

  left_arr = [0] * x
  right_arr = [0] * y

  for i in range(x):
    left_arr[i] = arr[left + i]

  for j in range(y):
    right_arr[j] = arr[mid + 1 + j]

  i = j = 0
  k = left

  while i < x and j < y:
    if left_arr[i] <= right_arr[j]:
      arr[k] = left_arr[i]
      i += 1
    else:
      arr[k] = right_arr[j]
      j += 1
      count += x - i
      k += 1

  while i < x:
    arr[k] = left_arr[i]
    i += 1
    k += 1

  while j < y:
    arr[k] = right_arr[j]
    j += 1
    k += 1

  return count

def Number_of_pairs(arr, left, right):
  total_pairs = 0
  if left < right:
    mid = (left + right) // 2
    total_pairs += Number_of_pairs(arr, left, mid)
    total_pairs += Number_of_pairs(arr, mid + 1, right)
    total_pairs += merge_and_count(arr, left, mid, right)
  return total_pairs

N = int(file.readline())
H = list(map(int, file.readline().split()))
pairs = Number_of_pairs(H, 0, N - 1)

output_file = open("output3.txt", "a")
output_file.write(str(pairs))

file.close()
output_file.close()