# -*- coding: utf-8 -*-
"""CSE221_Lab-02_Task-02(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KI7u6BsKGP4qePypUcS_uoF0gJPGCZsG
"""

#Task 2 b
file = open("input2b.txt", "r")
N = int(file.readline())
a1 = file.readline()
M = int(file.readline())
a2 = file.readline()
Alice = list(map(int, a1.split()))
Bob = list(map(int, a2.split()))

def merge(arr1, arr2):
    merged_list = []
    i, j = 0, 0

    while i < len(arr1) and j < len(arr2):
        if arr1[i] < arr2[j]:
            merged_list.append(arr1[i])
            i += 1
        else:
            merged_list.append(arr2[j])
            j += 1

    merged_list.extend(arr1[i:])
    merged_list.extend(arr2[j:])

    return merged_list

P = merge(Alice, Bob)

output_file = open('output2b.txt', "a")
for i in P:
  output_file.write(str(i) + " ")

file.close()
output_file.close()