# -*- coding: utf-8 -*-
"""CSE221_Lab-02_Task-02(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZrOQK6fLFvNVVzIew3nlaWV8Z9m8oQz
"""

#Task- 02 a
file = open("input2a.txt", "r")
N = int(file.readline())
a1 = file.readline()
M = int(file.readline())
a2 = file.readline()

def merge(arr1, arr2):
  i = j = k = 0
  new_arr = []
  while i < len(arr1) and j < len(arr2):
    if arr1[i] < arr2[j]:
      new_arr.append(arr1[i])
      i += 1

    else:
      new_arr.append(arr2[j])
      j += 1

    k += 1

  while i < len(arr1):
    new_arr.append(arr1[i])
    i += 1
    k += 1

  while j < len(arr2):
    new_arr.append(arr2[j])
    j += 1
    k += 1

  return new_arr

Alice = list(map(int, a1.split()))
Bob = list(map(int, a2.split()))
P = merge(Alice, Bob)

output_file = open("output2a.txt", "a")
for r in P:
  output_file.write(str(r) + " ")