# -*- coding: utf-8 -*-
"""CSE221_Lab-02_Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEnxHAZWWXmK0iVEGvh6pYxSZfSCjlxW
"""

#Task- 04
file = open("input4.txt","r")

def max_activities(arr1, arr2):
  flag = False
  if arr2 == []:
    flag = True
    arr2.append([arr1[0][1], arr1[0][0]])
    arr1.pop(0)

  else:
    for i in arr1:
      if i[1] == arr2[len(arr2) - 1][1]:
        flag = True
        arr2.append([i[1], i[0]])
        arr1.remove(i)
        break

    if flag == False:
      for i in arr1:
        if i[1] > arr2[len(arr2) - 1][1]:
          flag = True
          arr2.append([i[1], i[0]])
          arr1.remove(i)
          break

  if flag == True:
    max_activities(arr1, arr2)

  return arr2

t = file.readline().split(" ")
N = int(t[0])
M = int(t[1])
times = []
for i in range(0, N):
  Si, Ei = map(int, file.readline().split())
  times.append([Ei, Si])
sorted_times = sorted(times)

max_accomplished_activities = 0
for i in range(M):
  max_accomplished_activities += len(max_activities(sorted_times, []))

output_file = open('output4.txt','a')
output_file.write(f'{max_accomplished_activities}')

file.close()
output_file.close()