# -*- coding: utf-8 -*-
"""CSE221_Lab-02_ Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYQNdMNJJiGvx1DpG6CQgrF71kt12oCi
"""

#Task- 03
file = open('input3.txt', 'r')

N = int(file.readline())
times = []
for k in range(N):
  Si, Ei = map(int, file.readline().split())
  times.append((Si, Ei))

def maximum_accomplished(times):
  times = sorted(times, key=lambda x: x[1])
  max_total_tasks = []
  ending_time = 0

  for task in times:
    start_time, end_time = task
    if start_time >= ending_time:
      max_total_tasks.append(task)
      ending_time = end_time

  return max_total_tasks

Max_tasks = maximum_accomplished(times)

output_file = open('output3.txt', 'a')
output_file.write(f'{len(Max_tasks)} \n')
for i in Max_tasks:
  output_file.write(f'{i[0]} {i[1]} \n')

file.close()
output_file.close()