# -*- coding: utf-8 -*-
"""CSE221_Lab-02_Task-01(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vD7Iwrx8pa4KszOS9KnVRguEwiycF_s5
"""

#Task- 01 b
file = open("input1b.txt", "r")
T = file.readline()
L = file.readline()

TL = T.split()
N1 = 0
N2 = int(TL[0]) - 1
S = int(TL[1])
int_list = list(map(int, L.split()))

output_file = open("output1b.txt", "a")
flag = False
while N1 < N2:
  int_sum = int_list[N1] + int_list[N2]
  if int_sum == S:
    output_file.write(f"{N1+1} {N2+1}")
    flag = True
    break
  elif int_sum > S:
    N2 = N2 - 1
  elif int_sum < S:
    N1 = N1 + 1

if flag == False:
  output_file.write(f"Impossible")