# -*- coding: utf-8 -*-
"""CSE221_Lab-06_Task-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S9poz_aVA6gJ5WEn5BR_MG6NaPY3hogu
"""

#Task- 03
file = open("input3_2.txt", "r")
output_file = open('output3_2.txt','w')
N, M = map(int, file.readline().split())
G = []
for i in range(M):
  u, v = map(int, file.readline().split())
  G.append((u, v))

def friend_circle_size(N, K, G):
  parent = list(range(N + 1))
  s = [1] * (N + 1)

  def set_finding(x):
    if parent[x] != x:
      parent[x] = set_finding(parent[x])
    return parent[x]

  def set_of_U(x, y):
    rx = set_finding(x)
    ry = set_finding(y)
    if rx != ry:
      parent[rx] = ry
      s[ry] += s[rx]

  sets = []
  for vtx in G:
    a, b = vtx
    set_of_U(a, b)
    sets.append(s[set_finding(a)])

  return sets

R = friend_circle_size(N, M, G)
for r in R:
  output_file.write(str(r) + "\n")

file.close()
output_file.close()